### ISSUE TITLE
TypeError on d.ts linting

### ISSUE THREAD

**Issue by azdanov** [jorgegonzalez/zoe#44]
I get `TypeError: Cannot read property 'body' of null` but can't pinpoint the origin. It only happens on this `d.ts` file, others are ok.

I've used [dts-gen](https://github.com/Microsoft/dts-gen) to generate this `d.ts` file.

<details>
<summary>trace log</summary>

```
TypeError: Cannot read property 'body' of null
    at checkForConstructor (/Users/implaier/PhpstormProjects/zoe/node_modules/eslint/lib/rules/no-useless-constructor.js:167:42)
    at listeners.(anonymous function).forEach.listener (/Users/implaier/PhpstormProjects/zoe/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/implaier/PhpstormProjects/zoe/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/Users/implaier/PhpstormProjects/zoe/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/implaier/PhpstormProjects/zoe/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/implaier/PhpstormProjects/zoe/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/Users/implaier/PhpstormProjects/zoe/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at Traverser.enter [as _enter] (/Users/implaier/PhpstormProjects/zoe/node_modules/eslint/lib/linter.js:865:28)
    at Traverser._traverse (/Users/implaier/PhpstormProjects/zoe/node_modules/eslint/lib/util/traverser.js:132:14)
```
</details>

<details>

<summary>remark-parse.d.ts</summary>

```typescript
/** Declaration file generated by dts-gen */
/* eslint-disable camelcase, typescript/no-namespace, no-unused-vars, no-redeclare */

export = remark_parse;

declare function remark_parse(options: any): void;

declare namespace remark_parse {
  class Parser {
    constructor(doc: any, file: any);

    enterBlock(): any;

    enterLink(): any;

    enterList(): any;

    exitStart(): any;

    parse(): any;

    setOptions(options: any): any;

    tokenizeBlock(value: any, location: any, ...args: any[]): any;

    tokenizeFactory(type: any, ...args: any[]): any;

    tokenizeInline(value: any, location: any, ...args: any[]): any;
  }

  const prototype: {};

  namespace Parser {
    namespace prototype {
      const blockMethods: string[];

      const inlineMethods: string[];

      const interruptBlockquote: (string[])[];

      const interruptList: (string[])[];

      const interruptParagraph: (string[])[];

      const options: {
        blocks: string[];
        commonmark: boolean;
        footnotes: boolean;
        gfm: boolean;
        pedantic: boolean;
        position: boolean;
      };

      function enterBlock(): any;

      function enterLink(): any;

      function enterList(): any;

      function exitStart(): any;

      function parse(): any;

      function setOptions(options: any): any;

      function tokenizeBlock(value: any, location: any, ...args: any[]): any;

      function tokenizeFactory(type: any, ...args: any[]): any;

      function tokenizeInline(value: any, location: any, ...args: any[]): any;

      namespace blockTokenizers {
        function atxHeading(eat: any, value: any, silent: any): any;

        function blockquote(eat: any, value: any, silent: any): any;

        function definition(eat: any, value: any, silent: any): any;

        function fencedCode(eat: any, value: any, silent: any): any;

        function footnote(eat: any, value: any, silent: any): any;

        function html(eat: any, value: any, silent: any): any;

        function indentedCode(eat: any, value: any, silent: any): any;

        function list(eat: any, value: any, silent: any): any;

        function newline(eat: any, value: any, silent: any): any;

        function paragraph(eat: any, value: any, silent: any): any;

        function setextHeading(eat: any, value: any, silent: any): any;

        function table(eat: any, value: any, silent: any): any;

        function thematicBreak(eat: any, value: any, silent: any): any;

        namespace atxHeading {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.atxHeading
          const prototype: any;
        }

        namespace blockquote {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.blockquote
          const prototype: any;
        }

        namespace definition {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.definition
          const notInBlock: any;

          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.definition
          const notInList: any;

          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.definition
          const prototype: any;
        }

        namespace fencedCode {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.fencedCode
          const prototype: any;
        }

        namespace footnote {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.footnote
          const notInBlock: any;

          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.footnote
          const notInList: any;

          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.footnote
          const prototype: any;
        }

        namespace html {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.html
          const prototype: any;
        }

        namespace indentedCode {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.indentedCode
          const prototype: any;
        }

        namespace list {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.list
          const prototype: any;
        }

        namespace newline {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.newline
          const prototype: any;
        }

        namespace paragraph {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.paragraph
          const prototype: any;
        }

        namespace setextHeading {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.setextHeading
          const prototype: any;
        }

        namespace table {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.table
          const prototype: any;
        }

        namespace thematicBreak {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.thematicBreak
          const prototype: any;
        }
      }

      namespace enterBlock {
        const prototype: {};
      }

      namespace enterLink {
        const prototype: {};
      }

      namespace enterList {
        const prototype: {};
      }

      namespace exitStart {
        const prototype: {};
      }

      namespace inlineTokenizers {
        function autoLink(eat: any, value: any, silent: any): any;

        function code(eat: any, value: any, silent: any): any;

        function deletion(eat: any, value: any, silent: any): any;

        function emphasis(eat: any, value: any, silent: any): any;

        function escape(eat: any, value: any, silent: any): any;

        function html(eat: any, value: any, silent: any): any;

        function link(eat: any, value: any, silent: any): any;

        function reference(eat: any, value: any, silent: any): any;

        function strong(eat: any, value: any, silent: any): any;

        function text(eat: any, value: any, silent: any): any;

        function url(eat: any, value: any, silent: any): any;

        namespace autoLink {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.autoLink
          const locator: any;

          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.autoLink
          const notInLink: any;

          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.autoLink
          const prototype: any;
        }

        namespace code {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.code
          const locator: any;

          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.code
          const prototype: any;
        }

        namespace deletion {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.deletion
          const locator: any;

          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.deletion
          const prototype: any;
        }

        namespace emphasis {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.emphasis
          const locator: any;

          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.emphasis
          const prototype: any;
        }

        namespace escape {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.escape
          const locator: any;

          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.escape
          const prototype: any;
        }

        namespace html {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.html
          const locator: any;

          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.html
          const prototype: any;
        }

        namespace link {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.link
          const locator: any;

          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.link
          const prototype: any;
        }

        namespace reference {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.reference
          const locator: any;

          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.reference
          const prototype: any;
        }

        namespace strong {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.strong
          const locator: any;

          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.strong
          const prototype: any;
        }

        namespace text {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.text
          const prototype: any;
        }

        namespace url {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.url
          const locator: any;

          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.url
          const notInLink: any;

          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.url
          const prototype: any;
        }
      }

      namespace parse {
        const prototype: {};
      }

      namespace setOptions {
        const prototype: {};
      }

      namespace tokenizeBlock {
        const prototype: {};
      }

      namespace tokenizeFactory {
        const prototype: {};
      }

      namespace tokenizeInline {
        const prototype: {};
      }
    }
  }
}
```
</details>

**Comment by jorgegonzalez** [comment]
I can't reproduce. Where are you seeing this error? Can you send a screenshot?

**Comment by azdanov** [comment]
With `remark-parse.d.ts`:

<img width="1392" alt="screen shot 2018-07-28 at 04 47 33" src="https://user-images.githubusercontent.com/6123841/43351849-5e6b8626-9221-11e8-8a89-9b710dc9468c.png">

Without `remark-parse.d.ts`:

<img width="1392" alt="screen shot 2018-07-28 at 04 51 04" src="https://user-images.githubusercontent.com/6123841/43351877-d303a4be-9221-11e8-98e5-1628d455645a.png">

**Comment by jorgegonzalez** [comment]
Where is `utilities/typings`?

**Comment by azdanov** [comment]
I couldn't include it with `feature/docs`, since `lint-staged` rejected the commit.

I've included the file, `remark-parse.d.ts`, which causes problems.

**Comment by jorgegonzalez** [comment]
? where is `remark-parse.d.ts`

**Comment by azdanov** [comment]
This thread's first post, I've hidden it in details view.

Here's the file again:

```typescript
/** Declaration file generated by dts-gen */
/* eslint-disable camelcase, typescript/no-namespace, no-unused-vars, no-redeclare */

export = remark_parse;

declare function remark_parse(options: any): void;

declare namespace remark_parse {
  class Parser {
    constructor(doc: any, file: any);

    enterBlock(): any;

    enterLink(): any;

    enterList(): any;

    exitStart(): any;

    parse(): any;

    setOptions(options: any): any;

    tokenizeBlock(value: any, location: any, ...args: any[]): any;

    tokenizeFactory(type: any, ...args: any[]): any;

    tokenizeInline(value: any, location: any, ...args: any[]): any;
  }

  const prototype: {};

  namespace Parser {
    namespace prototype {
      const blockMethods: string[];

      const inlineMethods: string[];

      const interruptBlockquote: (string[])[];

      const interruptList: (string[])[];

      const interruptParagraph: (string[])[];

      const options: {
        blocks: string[];
        commonmark: boolean;
        footnotes: boolean;
        gfm: boolean;
        pedantic: boolean;
        position: boolean;
      };

      function enterBlock(): any;

      function enterLink(): any;

      function enterList(): any;

      function exitStart(): any;

      function parse(): any;

      function setOptions(options: any): any;

      function tokenizeBlock(value: any, location: any, ...args: any[]): any;

      function tokenizeFactory(type: any, ...args: any[]): any;

      function tokenizeInline(value: any, location: any, ...args: any[]): any;

      namespace blockTokenizers {
        function atxHeading(eat: any, value: any, silent: any): any;

        function blockquote(eat: any, value: any, silent: any): any;

        function definition(eat: any, value: any, silent: any): any;

        function fencedCode(eat: any, value: any, silent: any): any;

        function footnote(eat: any, value: any, silent: any): any;

        function html(eat: any, value: any, silent: any): any;

        function indentedCode(eat: any, value: any, silent: any): any;

        function list(eat: any, value: any, silent: any): any;

        function newline(eat: any, value: any, silent: any): any;

        function paragraph(eat: any, value: any, silent: any): any;

        function setextHeading(eat: any, value: any, silent: any): any;

        function table(eat: any, value: any, silent: any): any;

        function thematicBreak(eat: any, value: any, silent: any): any;

        namespace atxHeading {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.atxHeading
          const prototype: any;
        }

        namespace blockquote {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.blockquote
          const prototype: any;
        }

        namespace definition {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.definition
          const notInBlock: any;

          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.definition
          const notInList: any;

          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.definition
          const prototype: any;
        }

        namespace fencedCode {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.fencedCode
          const prototype: any;
        }

        namespace footnote {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.footnote
          const notInBlock: any;

          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.footnote
          const notInList: any;

          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.footnote
          const prototype: any;
        }

        namespace html {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.html
          const prototype: any;
        }

        namespace indentedCode {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.indentedCode
          const prototype: any;
        }

        namespace list {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.list
          const prototype: any;
        }

        namespace newline {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.newline
          const prototype: any;
        }

        namespace paragraph {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.paragraph
          const prototype: any;
        }

        namespace setextHeading {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.setextHeading
          const prototype: any;
        }

        namespace table {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.table
          const prototype: any;
        }

        namespace thematicBreak {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.blockTokenizers.thematicBreak
          const prototype: any;
        }
      }

      namespace enterBlock {
        const prototype: {};
      }

      namespace enterLink {
        const prototype: {};
      }

      namespace enterList {
        const prototype: {};
      }

      namespace exitStart {
        const prototype: {};
      }

      namespace inlineTokenizers {
        function autoLink(eat: any, value: any, silent: any): any;

        function code(eat: any, value: any, silent: any): any;

        function deletion(eat: any, value: any, silent: any): any;

        function emphasis(eat: any, value: any, silent: any): any;

        function escape(eat: any, value: any, silent: any): any;

        function html(eat: any, value: any, silent: any): any;

        function link(eat: any, value: any, silent: any): any;

        function reference(eat: any, value: any, silent: any): any;

        function strong(eat: any, value: any, silent: any): any;

        function text(eat: any, value: any, silent: any): any;

        function url(eat: any, value: any, silent: any): any;

        namespace autoLink {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.autoLink
          const locator: any;

          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.autoLink
          const notInLink: any;

          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.autoLink
          const prototype: any;
        }

        namespace code {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.code
          const locator: any;

          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.code
          const prototype: any;
        }

        namespace deletion {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.deletion
          const locator: any;

          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.deletion
          const prototype: any;
        }

        namespace emphasis {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.emphasis
          const locator: any;

          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.emphasis
          const prototype: any;
        }

        namespace escape {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.escape
          const locator: any;

          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.escape
          const prototype: any;
        }

        namespace html {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.html
          const locator: any;

          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.html
          const prototype: any;
        }

        namespace link {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.link
          const locator: any;

          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.link
          const prototype: any;
        }

        namespace reference {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.reference
          const locator: any;

          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.reference
          const prototype: any;
        }

        namespace strong {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.strong
          const locator: any;

          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.strong
          const prototype: any;
        }

        namespace text {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.text
          const prototype: any;
        }

        namespace url {
          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.url
          const locator: any;

          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.url
          const notInLink: any;

          // Too-deep object hierarchy from remark_parse.Parser.prototype.inlineTokenizers.url
          const prototype: any;
        }
      }

      namespace parse {
        const prototype: {};
      }

      namespace setOptions {
        const prototype: {};
      }

      namespace tokenizeBlock {
        const prototype: {};
      }

      namespace tokenizeFactory {
        const prototype: {};
      }

      namespace tokenizeInline {
        const prototype: {};
      }
    }
  }
}
```

**Comment by jorgegonzalez** [comment]
Sorry must have missed that. I can reproduce now.

**Comment by jorgegonzalez** [comment]
Seems like a bug https://github.com/eslint/typescript-eslint-parser/issues/496
