### ISSUE TITLE
Editor Integration

### ISSUE THREAD

**Issue by azdanov** [jorgegonzalez/zoe#57]
Same for both.

```json
{
  "extends": "eslint-config-zoe"
}
```

```json
{
  "extends": "zoe"
}
```

```txt
Error: Failed to load plugin unicorn: Cannot find module 'eslint-plugin-unicorn'
Referenced from: /Users/implaier/PhpstormProjects/azdanov.github.io/.eslintrc

Error: Failed to load plugin unicorn: Cannot find module 'eslint-plugin-unicorn'
Referenced from: /Users/implaier/PhpstormProjects/azdanov.github.io/.eslintrc
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at Plugins.load (/Users/implaier/PhpstormProjects/azdanov.github.io/node_modules/eslint/lib/config/plugins.js:96:29)
    at Array.forEach (<anonymous>)
    at Plugins.loadAll (/Users/implaier/PhpstormProjects/azdanov.github.io/node_modules/eslint/lib/config/plugins.js:157:21)
    at loadFromDisk (/Users/implaier/PhpstormProjects/azdanov.github.io/node_modules/eslint/lib/config/config-file.js:506:35)
    at load (/Users/implaier/PhpstormProjects/azdanov.github.io/node_modules/eslint/lib/config/config-file.js:564:20)
    at configExtends.reduceRight (/Users/implaier/PhpstormProjects/azdanov.github.io/node_modules/eslint/lib/config/config-file.js:430:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (/Users/implaier/PhpstormProjects/azdanov.github.io/node_modules/eslint/lib/config/config-file.js:408:26)
Process finished with exit code -1
```

**Comment by azdanov** [comment]
I have resolved this issue, so closing.

The correct way is to install zoe package, and then using `zoe` config becomes possible.
