### ISSUE TITLE
Error During Lint

### ISSUE THREAD

**Issue by azdanov** [jorgegonzalez/zoe#58]
🤷‍♂️ I will try to find where this originates from. [Project](https://github.com/azdanov/azdanov.github.io) where I tried running zoe on.

```txt
Zoe 1.10.6
TypeError: Cannot read property 'body' of null
    at checkForConstructor (/Users/implaier/PhpstormProjects/azdanov.github.io/node_modules/zoe/node_modules/eslint/lib/rules/no-useless-constructor.js:167:42)
    at listeners.(anonymous function).forEach.listener (/Users/implaier/PhpstormProjects/azdanov.github.io/node_modules/zoe/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/implaier/PhpstormProjects/azdanov.github.io/node_modules/zoe/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/Users/implaier/PhpstormProjects/azdanov.github.io/node_modules/zoe/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/implaier/PhpstormProjects/azdanov.github.io/node_modules/zoe/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/implaier/PhpstormProjects/azdanov.github.io/node_modules/zoe/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/Users/implaier/PhpstormProjects/azdanov.github.io/node_modules/zoe/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at Traverser.enter [as _enter] (/Users/implaier/PhpstormProjects/azdanov.github.io/node_modules/zoe/node_modules/eslint/lib/linter.js:865:28)
    at Traverser._traverse (/Users/implaier/PhpstormProjects/azdanov.github.io/node_modules/zoe/node_modules/eslint/lib/util/traverser.js:132:14)
```

**Comment by azdanov** [comment]
Latest PR #59 solved this for me.
