### ISSUE TITLE
Cannot read property 'sync' of undefined

### ISSUE THREAD

**Issue by KidkArolis** [jorgegonzalez/zoe#83]
Just installed zoe and got this when trying to run:

```
karolis$ zoe
Zoe 1.24.2
TypeError: Cannot read property 'sync' of undefined
    at Program (/Users/karolis/lessnoise/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js:166:59)
    at listeners.(anonymous function).forEach.listener (/Users/karolis/lessnoise/node_modules/zoe/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/karolis/lessnoise/node_modules/zoe/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/karolis/lessnoise/node_modules/zoe/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/karolis/lessnoise/node_modules/zoe/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/karolis/lessnoise/node_modules/zoe/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/Users/karolis/lessnoise/node_modules/zoe/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:632:23)
    at nodeQueue.forEach.traversalInfo (/Users/karolis/lessnoise/node_modules/zoe/node_modules/eslint/lib/linter.js:750:28)
    at Array.forEach (<anonymous>)
    at runRules (/Users/karolis/lessnoise/node_modules/zoe/node_modules/eslint/lib/linter.js:746:15)
    at Linter._verifyWithoutProcessors (/Users/karolis/lessnoise/node_modules/zoe/node_modules/eslint/lib/linter.js:891:31)
    at preprocess.map.textBlock (/Users/karolis/lessnoise/node_modules/zoe/node_modules/eslint/lib/linter.js:940:35)
    at Array.map (<anonymous>)
    at Linter.verify (/Users/karolis/lessnoise/node_modules/zoe/node_modules/eslint/lib/linter.js:939:42)
    at Linter.verifyAndFix (/Users/karolis/lessnoise/node_modules/zoe/node_modules/eslint/lib/linter.js:1032:29)
```

Will have a closer look to see if I can fix this. But posting in the meantime in case you know what's going wrong.

**Comment by KidkArolis** [comment]
I think I just had too many things installed with their own eslints (e.g. standard, prettier-standard, etc.). After unistalling those and installing zoe, it's working fine.
