### ISSUE TITLE
Error with eslint >6

### ISSUE THREAD

**Issue by cdfa** [jorgegonzalez/zoe#99]
Hi, when using the `eslint` config with `eslint@^6.0.0` (as required by some other plugins I'm using), I get the following error. This is because there is an error in `eslint-config-react-app`, as is already reported [here](https://github.com/facebook/create-react-app/issues/7284). The Facebook team seems reluctant to fix it, so could you switch out `eslint-config-react-app` for `eslint-config-react-app-eslint-six`, as the thread suggests?

```
Error: ESLint configuration in .eslintrc.json » eslint-config-zoe/react » eslint-config-react-app is invalid:
- Property "overrides" is the wrong type (expected array but got `{"files":["**/*.ts","**/*.tsx"],"parser":"@typescript-eslint/parser","parserOptions":{"ecmaVersion":2018,"sourceType":"module","ecmaFeatures":{"jsx":true},"warnOnUnsupportedTypeScriptVersion":true},"plugins":["@typescript-eslint"],"rules":{"default-case":"off","no-dupe-class-members":"off","@typescript-eslint/no-angle-bracket-type-assertion":"warn","no-array-constructor":"off","@typescript-eslint/no-array-constructor":"warn","@typescript-eslint/no-namespace":"error","no-unused-vars":"off","@typescript-eslint/no-unused-vars":["warn",{"args":"none","ignoreRestSiblings":true}],"no-useless-constructor":"off","@typescript-eslint/no-useless-constructor":"warn"}}`).
Referenced from: /home/cdfa/Projects/react-turn-reveal/node_modules/.registry.npmjs.org/eslint-config-zoe/1.28.3/node_modules/eslint-config-zoe/react.js
at validateConfigSchema (/home/cdfa/Projects/react-turn-reveal/node_modules/.registry.npmjs.org/eslint/6.1.0/node_modules/eslint/lib/shared/config-validator.js:286:15)
at ConfigArrayFactory._normalizeConfigData (/home/cdfa/Projects/react-turn-reveal/node_modules/.registry.npmjs.org/eslint/6.1.0/node_modules/eslint/lib/cli-engine/config-array-factory.js:469:9)
at ConfigArrayFactory._loadConfigData (/home/cdfa/Projects/react-turn-reveal/node_modules/.registry.npmjs.org/eslint/6.1.0/node_modules/eslint/lib/cli-engine/config-array-factory.js:414:21)
at ConfigArrayFactory._loadExtendedShareableConfig (/home/cdfa/Projects/react-turn-reveal/node_modules/.registry.npmjs.org/eslint/6.1.0/node_modules/eslint/lib/cli-engine/config-array-factory.js:714:21)
at ConfigArrayFactory._loadExtends (/home/cdfa/Projects/react-turn-reveal/node_modules/.registry.npmjs.org/eslint/6.1.0/node_modules/eslint/lib/cli-engine/config-array-factory.js:613:25)
at ConfigArrayFactory._normalizeObjectConfigDataBody (/home/cdfa/Projects/react-turn-reveal/node_modules/.registry.npmjs.org/eslint/6.1.0/node_modules/eslint/lib/cli-engine/config-array-factory.js:545:25)
at _normalizeObjectConfigDataBody.next (<anonymous>)
at ConfigArrayFactory._normalizeObjectConfigData (/home/cdfa/Projects/react-turn-reveal/node_modules/.registry.npmjs.org/eslint/6.1.0/node_modules/eslint/lib/cli-engine/config-array-factory.js:491:20)
at _normalizeObjectConfigData.next (<anonymous>)
at ConfigArrayFactory._normalizeObjectConfigDataBody (/home/cdfa/Projects/react-turn-reveal/node_modules/.registry.npmjs.org/eslint/6.1.0/node_modules/eslint/lib/cli-engine/config-array-factory.js:545:25)
```

**Comment by cdfa** [comment]
Actually, it seems like there will be a release quite soon, never mind :)

**Comment by jorgegonzalez** [comment]
Yeah I'm aware of this. Feel free to open a PR to fix it here when they release.
